### ISSUE TITLE
The `column_index` query parameter is not supported

### ISSUE THREAD

**Issue by euf** [quandl/Matlab#11]
Hi,

Thanks for the great package!
Unfortunately, I found Quandl API is not fully supported.
Official documentation https://www.quandl.com/docs/api says:

> Request a specific column by passing the `column_index=n` parameter. Column `0` is the date column and is always returned. Data begins at column `1`.

At the moment, there is no way to use parameter `column_index` in the request.
This seems to be a real problem, because performing something like

```matlab
usd = Quandl.get( ... 
    'CURRFX/USDRUB', 'start_date',2009-01-01,'end_date',2010-01-01,'type','ts');
```

returns a really messy cell array of individual `tscollection` objects.

*Not really sure, maybe this is another one bug.*

**Comment by jbyck** [comment]
The current version of this package does not support the column_index parameter. We are planning to address that in a future version.
