### ISSUE TITLE
Getting Errors.  May need to review the API in full again, but would appreciate error correct!

### ISSUE THREAD

**Issue by MikeEME** [quandl/Matlab#13]
MATLAB 2016b Windows 10 64bit

`data = Quandl.get('NSE/OIL');`
Response stream is undefined
 below is a Java Error dump (truncated):
Error using urlread2.urlread2 (line 217)
Java exception occurred:
java.io.IOException: Server returned HTTP response code: 400 for URL:
https://www.quandl.com/api/v3/datasets/NSE/OIL.csv?&api_key=
(_mykey_)&auth_token= (`mytoken`)_&sort_order=desc

Error in Quandl.api (line 37)
    [response, extras] = urlread2.urlread2(url, 'GET', '', headers);

Error in Quandl.get (line 124)
    csv = Quandl.api(path, 'params', params);

**Comment by RaymondMcT** [comment]
Is there a space in your api key?
