### ISSUE TITLE
Unable to connect: connection timed out

### ISSUE THREAD

**Issue by erlendn** [quandl/Matlab#15]
Hello, 

After downloading both +Quandl and +urlread2 to my current folder I am getting an error message when trying to retrieve data. Any advice if this is an issue with the Matlab package for quandl, or is there an issue with connecting from my side? 

Matlab: 

>> Quandl.api_key('XXXXX');

>> data = Quandl.get('NSE/OIL');

Response stream is undefined
 below is a Java Error dump (truncated):
Error using urlread2.urlread2 (line 217)
Java exception occurred:
java.net.ConnectException: Connection timed out: connect

Error in Quandl.api (line 38)
    [response, extras] = urlread2.urlread2(url, 'GET', '', headers);

Error in Quandl.get (line 124)
    csv = Quandl.api(path, 'params', params);

**Comment by somethinrother** [comment]
Hi @erlendn,

We tried to recreate the issue, but everything seems to be working fine on our end. It's possible it could be a firewall or system update issue on your end. If you work in an office we recommend contacting your administrator to see if they are blocking any connections. Let us know if that helps and if not please feel free to re-open the ticket.
